---

inherit_gem:
  argon-rubocop: config/rubocop.yml


Style/Documentation:
  Exclude:
    - lib/argon/rubocop.rb
    - lib/argon/rubocop/config.rb

Style/Filename:
  Exclude:
    - lib/argon-rubocop.rb

Style/FrozenSTringLiteralComment:
  Enabled: false
