Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - '*.gemspec'
    - Gemfile
    - Rakefile
    - db/migrate/*

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/ClassLength:
  Severity: refactor

Metrics/LineLength:
  Max: 100
  Severity: refactor

# Prefer Metrics/AbcSize as a metric
Metrics/MethodLength:
  Severity: refactor

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false
