inherit_from: rubocop.yml

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - '*.gemspec'
    - Gemfile
    - Rakefile
    - db/migrate/*
